version: 2

models:
  - name: stg_olist_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: customer_unique_id
    tests:
      - not_null
